{"name": "test_authentication_error_openai", "status": "passed", "description": "Test OpenAI authentication error produces standard format.", "attachments": [{"name": "log", "source": "e79bcbfc-b0f3-4b65-aa8a-9979cf92fd2a-attachment.txt", "type": "text/plain"}], "start": 1757711148505, "stop": 1757711148505, "uuid": "729ce8a6-b69f-4cff-8fee-4e935220f474", "historyId": "64b15c7d88e8d68df16f5d90ec393857", "testCaseId": "64b15c7d88e8d68df16f5d90ec393857", "fullName": "tests.unit.test_standardized_llm_errors.TestStandardizedErrors#test_authentication_error_openai", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_standardized_llm_errors"}, {"name": "subSuite", "value": "TestStandardizedErrors"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "99272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_standardized_llm_errors"}], "titlePath": ["tests", "unit", "test_standardized_llm_errors.py", "TestStandardizedErrors"]}