{"name": "test_rate_limit_error_handling", "status": "passed", "description": "Test handling of 429 rate limit errors", "attachments": [{"name": "log", "source": "8a22117e-6ec5-44c2-8b71-f47ae10b07cb-attachment.txt", "type": "text/plain"}], "start": 1757656823733, "stop": 1757656823733, "uuid": "9b17e919-6c17-438f-a8cc-81999b76aa88", "historyId": "dd5ada2a2050113c57f087410aefb46f", "testCaseId": "dd5ada2a2050113c57f087410aefb46f", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_rate_limit_error_handling", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "37492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}