{"name": "test_connection_timeout[OpenAIAdapter-gpt-4]", "status": "passed", "description": "Test handling of connection timeouts", "attachments": [{"name": "log", "source": "da8f93e7-1de9-475a-9dc4-b02bdd2c2ad4-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "adapter_class", "value": "<class 'app.services.llm_adapters.OpenAIAdapter'>"}, {"name": "model", "value": "'gpt-4'"}], "start": 1757656801470, "stop": 1757656801470, "uuid": "5ef1983e-6f5d-4fab-925a-4701ee4e4d19", "historyId": "c50371b1e9be678476f086ebbc3a13bd", "testCaseId": "ba9cd9bb1e60e0917f6d0c6ca20e3841", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestAdapterErrorScenarios#test_connection_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestAdapterErrorScenarios"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "36177-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestAdapterErrorScenarios"]}