{"name": "test_gemini_adapter_authentication_error", "status": "passed", "description": "Test Gemini adapter handles 401 authentication errors.", "attachments": [{"name": "log", "source": "7e2ad2c2-1888-45d0-b022-14292ed41316-attachment.txt", "type": "text/plain"}], "start": 1757656795472, "stop": 1757656795473, "uuid": "c962340f-e7da-406b-8a1d-ea53f3d73905", "historyId": "9898fdd7a9b94ab308f7eb1411428a27", "testCaseId": "9898fdd7a9b94ab308f7eb1411428a27", "fullName": "tests.test_llm_adapters_comprehensive.TestGeminiAdapter#test_gemini_adapter_authentication_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestGeminiAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "36177-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "test_llm_adapters_comprehensive.py", "TestGeminiAdapter"]}