{"name": "test_openai_adapter_timeout_error", "status": "passed", "description": "Test OpenAI adapter handles timeout errors.", "attachments": [{"name": "log", "source": "f549924b-7ab9-40c0-b538-99c5b394eb40-attachment.txt", "type": "text/plain"}], "start": 1757656627845, "stop": 1757656627846, "uuid": "79988070-4453-4b83-a0c4-4dc428b16ce8", "historyId": "7e3e71b770af1fb8c44d092d19ae57d9", "testCaseId": "7e3e71b770af1fb8c44d092d19ae57d9", "fullName": "tests.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_openai_adapter_timeout_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "29528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}