{"name": "test_invalid_api_key[OpenAIAdapter-gpt-4]", "status": "passed", "description": "Test handling of invalid API key errors", "attachments": [{"name": "log", "source": "bb617902-b1ca-44f4-879e-53c1f8366e9b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "adapter_class", "value": "<class 'app.services.llm_adapters.OpenAIAdapter'>"}, {"name": "model", "value": "'gpt-4'"}], "start": 1757656801561, "stop": 1757656801562, "uuid": "0e5d5852-a4a5-4c57-b9e4-4291c30d94cd", "historyId": "906708241d239479b1b9ac07c192071a", "testCaseId": "a48857aca520c162f89d61f76fff637c", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestAdapterErrorScenarios#test_invalid_api_key", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestAdapterErrorScenarios"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "36177-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestAdapterErrorScenarios"]}