{"name": "test_model_not_found_error", "status": "passed", "description": "Test model not found error format.", "attachments": [{"name": "log", "source": "3285befd-d715-4543-8220-8199e392b3d6-attachment.txt", "type": "text/plain"}], "start": 1757668150008, "stop": 1757668150009, "uuid": "1d17b41c-2373-45c2-b148-d3797b624da1", "historyId": "b50cf7517d95f2cb8d39af59776e0289", "testCaseId": "b50cf7517d95f2cb8d39af59776e0289", "fullName": "tests.unit.test_standardized_llm_errors.TestStandardizedErrors#test_model_not_found_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_standardized_llm_errors"}, {"name": "subSuite", "value": "TestStandardizedErrors"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "33649-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_standardized_llm_errors"}], "titlePath": ["tests", "unit", "test_standardized_llm_errors.py", "TestStandardizedErrors"]}