{"name": "test_authentication_error_openai", "status": "passed", "description": "Test OpenAI authentication error produces standard format.", "attachments": [{"name": "log", "source": "ea7a25ed-ac00-4bfc-9976-c73fc94681b9-attachment.txt", "type": "text/plain"}], "start": 1757656748903, "stop": 1757656748904, "uuid": "741b6c27-5381-4fec-9717-92c14d1e5bf2", "historyId": "64b15c7d88e8d68df16f5d90ec393857", "testCaseId": "64b15c7d88e8d68df16f5d90ec393857", "fullName": "tests.unit.test_standardized_llm_errors.TestStandardizedErrors#test_authentication_error_openai", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_standardized_llm_errors"}, {"name": "subSuite", "value": "TestStandardizedErrors"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "34153-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_standardized_llm_errors"}], "titlePath": ["tests", "unit", "test_standardized_llm_errors.py", "TestStandardizedErrors"]}