{"name": "test_rate_limit_error_handling", "status": "passed", "description": "Test handling of 429 rate limit errors", "attachments": [{"name": "log", "source": "f6715cff-7bb1-4504-846e-9137b2c9e8e6-attachment.txt", "type": "text/plain"}], "start": 1757668149716, "stop": 1757668149717, "uuid": "c929d6f9-2571-41a8-911c-7ce9273e4abc", "historyId": "dd5ada2a2050113c57f087410aefb46f", "testCaseId": "dd5ada2a2050113c57f087410aefb46f", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_rate_limit_error_handling", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "33649-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}