{"name": "test_rate_limit_error_handling", "status": "passed", "description": "Test handling of 429 rate limit errors", "attachments": [{"name": "log", "source": "927367e0-9989-4365-83df-100e7b405aa4-attachment.txt", "type": "text/plain"}], "start": 1757657444930, "stop": 1757657444931, "uuid": "0550aedb-3e58-40cf-b349-a92de5a77ec4", "historyId": "dd5ada2a2050113c57f087410aefb46f", "testCaseId": "dd5ada2a2050113c57f087410aefb46f", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_rate_limit_error_handling", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "59211-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}