{"name": "test_timeout_error", "status": "passed", "description": "Test timeout error produces standard format.", "attachments": [{"name": "log", "source": "6377ae36-509e-4cdb-8061-99fdd0348073-attachment.txt", "type": "text/plain"}], "start": 1757656748916, "stop": 1757656748917, "uuid": "f09859c3-35ed-4c4b-8d35-6f14ea48a65a", "historyId": "d47899ef8add7312ed513ce369486002", "testCaseId": "d47899ef8add7312ed513ce369486002", "fullName": "tests.unit.test_standardized_llm_errors.TestStandardizedErrors#test_timeout_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_standardized_llm_errors"}, {"name": "subSuite", "value": "TestStandardizedErrors"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "34153-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_standardized_llm_errors"}], "titlePath": ["tests", "unit", "test_standardized_llm_errors.py", "TestStandardizedErrors"]}