{"name": "test_openai_adapter_model_not_found_error", "status": "passed", "description": "Test OpenAI adapter handles 404 model not found errors.", "attachments": [{"name": "log", "source": "6b9c2400-45e1-47a3-a8b9-534520f62569-attachment.txt", "type": "text/plain"}], "start": 1757668156076, "stop": 1757668156077, "uuid": "1864ffa8-91d7-4af8-9ac7-2c4db62219b6", "historyId": "cc43cb517c5e4b98239c696d0bb294c6", "testCaseId": "cc43cb517c5e4b98239c696d0bb294c6", "fullName": "tests.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_openai_adapter_model_not_found_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "34209-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}